### ISSUE TITLE
Warnings when running tests

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-java#150]
I run:

```bash
./gradlew test
```
and I got warnings

<img width="1506" alt="Capture d’écran 2021-03-24 à 13 47 05" src="https://user-images.githubusercontent.com/20380692/112312846-898bce00-8ca7-11eb-8c59-97def6c517d5.png">

**Comment by niemannd** [comment]
This is intentional. 

decode uses a variable argumentlist to get all parameters for generic types.
See https://github.com/meilisearch/meilisearch-java/blob/5fa0dd5f2ff1e5d95db95d72d27c3ea22efb584b/src/main/java/com/meilisearch/sdk/json/JsonHandler.java#L21
To force the "parameters" parameter to be null, you have to supply null. 
Any other type would result in "parameters" being an array with the supplied type as first element.
This is the only way to test if the implementation behaves correctly in case parameters is null. 

I know that the chance that someone down the line triggers this case is slim, but as this is just a warning and does not "break" the build i think its a good idea to keep it in.

**Comment by curquiza** [comment]
Hello @niemannd! Thanks for your answer!
Isn't it possible to add a cast like for this test -> https://github.com/meilisearch/meilisearch-java/blob/da800ea8d3abc370f0ad796989965ab521ffa7ea/src/test/java/com/meilisearch/sdk/json/JacksonJsonHandlerTest.java#L33? So that it removes the warning. See #155 and maybe I'm doing something wrong
