### ISSUE TITLE
Add documentation to set up local environment for testing in Contributing.md

### ISSUE THREAD

**Issue by trangntt-016** [meilisearch/meilisearch-java#351]
Currently, there's no reference/documentation for setting up a local environment and exporting the masterKey in `Contributing.md`

Followed by https://docs.meilisearch.com/learn/getting_started/quick_start.html#step-1-setup-and-installation , there should be detailed guidelines for setting up local environment with:
- Docker
- cURL
- Homebrew
- Windows

**Comment by alallema** [comment]
Hi @trangntt-016,
Thank you for raising this issue. In order to keep the `Contributing` and `README` simple, we just had this command to set up the environment in the [`Development Workflow`](https://github.com/meilisearch/meilisearch-java/blob/main/CONTRIBUTING.md#development-workflow)
```
curl -L https://install.meilisearch.com | sh # download Meilisearch
./meilisearch --master-key=masterKey --no-analytics # run Meilisearch
./gradlew test IntegrationTest
```
We don't want to overwhelm the contributors by adding too much information. And these are, as you have shown available in the documentation.
