### ISSUE TITLE
The field "uid" in Task class should be "taskUid"

### ISSUE THREAD

**Issue by cursor99** [meilisearch/meilisearch-java#480]

**Comment by alallema** [comment]
Sorry for the delay, I will close this issue because:
The field `uid` should be in the `Task` class [see the object `Task` from Meilisearch](https://docs.meilisearch.com/reference/api/tasks.html#task-object). You talk about the field `taskUid` from [a summarized version of the task object](https://docs.meilisearch.com/reference/api/overview.html#response-body), which is currently handled with the class `TaskInfo` in this SDK.
