### ISSUE TITLE
Does Index could add compression algorithm?

### ISSUE THREAD

**Issue by Brook-Wilson-here** [meilisearch/meilisearch-java#584]
**Description**
Hi ! I found that this framework consumes a high amount of disk resources. Perhaps we can compress the data (gzip, zstd, snappy. etc)

**Basic example**
//Expected usage method
client.createIndex(String indexName,String primaryKey,String compressFunc);

**Other**
My Test Data
row       | datasize
77179   | 2.33 GB
421492 | 9.63 GB
336933 | 7.58 GB

**Comment by alallema** [comment]
Hi @Brook-Wilson-here,
Thanks for raising this issue, but it's not related to this repo but to the engine behavior, which is expected behavior; the engine team works daily to improve the engine. For more info, you can check our documentation about [storage](https://www.meilisearch.com/docs/learn/advanced/storage).
So I will close this issue
