### ISSUE TITLE
The primary key is snowflake ID, and progress will be lost after query and parsing

### ISSUE THREAD

**Issue by MorikGitHub** [meilisearch/meilisearch-java#671]
Stored data:
{
        "cultivateType": 2,
        "cultivateId": 1710533308552413209,
        "examineStatus": 0,
        "updater": "170",
        "ticketFlag": 0,
        "createTime": 这里是fastjson把时间转换后的LocalDateTime,
         "createTimeLong": 1696823214000,
}

Called sdk:
![image](https://github.com/meilisearch/meilisearch-java/assets/25000515/63952432-b9f5-483d-b51f-38062ff38b95)

 Query returned data:
{
	"hits": [{
		"cultivateType": 2,
		"cultivateId": 1710533308552413200,
		"examineStatus": 0,
		"updater": "170",
		"ticketFlag": 0,
                "createTime":1696823214000,
                "createTimeLong": 1696823214000
	}],
	"hitsPerPage": 10,
	"page": 1,
	"processingTimeMs": 1,
	"query": "",
	"totalHits": 11,
	"totalPages": 1
}

Question：
1、The primary key is snowflake ID, and progress will be lost after query and parsing.
2、Cannot query with LocalDateTime type. LocalDateTime needs to be converted to Long type in order to perform greater than or less than queries.

**Comment by curquiza** [comment]
Hey @MorikGitHub 

I'm sorry but I really don't understand your issue here. Looks like it's more related to any support need and not a request for feature or a bug fix.

You might have noticed when opening the issue we don't do support in this repo anymore.

<img width="1230" alt="Capture d’écran 2023-10-11 à 16 56 38" src="https://github.com/meilisearch/meilisearch-java/assets/20380692/d32e8d6f-9bb3-4bdb-89fd-85ebb4572f0f">


We are a small team, so we can’t spend much time doing support anymore :cry:. 
I would recommend going to our [Discord](https://discord.gg/meilisearch) instead. The community will be able to help you, no matter your question.

Thanks for using Meilisearch!
